--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 15.4

-- Started on 2024-03-27 13:14:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 26798)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 26803)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 26824)
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    text character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    user_id bigint NOT NULL,
    topic_id bigint NOT NULL
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 26823)
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 26817)
-- Name: topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topics (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.topics OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 26816)
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 26809)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(100) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 26808)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3346 (class 0 OID 26798)
-- Dependencies: 214
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.databasechangelog VALUES ('1.0.0', 'ilyam', 'liquibase/db.changelog-1.0.xml', '2024-03-27 05:35:21.909851', 1, 'EXECUTED', '9:f7917d0c7bd7e7a3b19b7fc430efbaf6', 'createTable tableName=users', '', NULL, '4.24.0', NULL, NULL, '1506921887');
INSERT INTO public.databasechangelog VALUES ('1.0.1', 'ilyam', 'liquibase/db.changelog-1.0.xml', '2024-03-27 05:35:21.91676', 2, 'EXECUTED', '9:e28c143658f89572a7e55ad1b40de381', 'createTable tableName=topics', '', NULL, '4.24.0', NULL, NULL, '1506921887');
INSERT INTO public.databasechangelog VALUES ('1.0.2', 'ilyam', 'liquibase/db.changelog-1.0.xml', '2024-03-27 05:35:21.924423', 3, 'EXECUTED', '9:8e72d911cd10cb62463bc2f69008601a', 'createTable tableName=messages', '', NULL, '4.24.0', NULL, NULL, '1506921887');
INSERT INTO public.databasechangelog VALUES ('1.0.3', 'ilyam', 'liquibase/db.changelog-1.0.xml', '2024-03-27 05:35:21.928813', 4, 'EXECUTED', '9:c15f9509ff6f6ec589e88dd453742bdb', 'addForeignKeyConstraint baseTableName=topics, constraintName=fk_topic_user, referencedTableName=users', '', NULL, '4.24.0', NULL, NULL, '1506921887');
INSERT INTO public.databasechangelog VALUES ('1.0.4', 'ilyam', 'liquibase/db.changelog-1.0.xml', '2024-03-27 05:35:21.932701', 5, 'EXECUTED', '9:36e4ac867ca2a0d372c1377fdd67a250', 'addForeignKeyConstraint baseTableName=messages, constraintName=fk_message_user, referencedTableName=users', '', NULL, '4.24.0', NULL, NULL, '1506921887');
INSERT INTO public.databasechangelog VALUES ('1.0.5', 'ilyam', 'liquibase/db.changelog-1.0.xml', '2024-03-27 05:35:21.938688', 6, 'EXECUTED', '9:921fa9be07156881f9d0370a7b9b3c13', 'addForeignKeyConstraint baseTableName=messages, constraintName=fk_message_topic, referencedTableName=topics', '', NULL, '4.24.0', NULL, NULL, '1506921887');


--
-- TOC entry 3347 (class 0 OID 26803)
-- Dependencies: 215
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.databasechangeloglock VALUES (1, false, NULL, NULL);


--
-- TOC entry 3353 (class 0 OID 26824)
-- Dependencies: 221
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.messages VALUES (3, 'string', '2024-03-27 05:42:03.932167', '2024-03-27 05:42:03.932167', 1, 3);
INSERT INTO public.messages VALUES (4, 'Новое сообщение!', '2024-03-27 05:44:03.66901', '2024-03-27 05:44:03.66901', 1, 3);
INSERT INTO public.messages VALUES (5, 'Ресторан супер!', '2024-03-27 12:15:00.738652', '2024-03-27 12:15:00.738652', 1, 3);
INSERT INTO public.messages VALUES (6, 'Вот это да!', '2024-03-27 12:15:09.877993', '2024-03-27 12:15:09.877993', 1, 3);
INSERT INTO public.messages VALUES (7, 'ВАуууу, просто супер!', '2024-03-27 12:15:18.306784', '2024-03-27 12:15:18.306784', 1, 3);
INSERT INTO public.messages VALUES (8, 'Леген .. подожди подожди.. дарно! Легендарно!', '2024-03-27 12:15:39.378932', '2024-03-27 12:15:39.378932', 1, 3);
INSERT INTO public.messages VALUES (9, 'компьютер супер!', '2024-03-27 12:19:05.631578', '2024-03-27 12:19:05.631578', 1, 4);
INSERT INTO public.messages VALUES (10, 'Восхитительно!', '2024-03-27 12:19:20.069706', '2024-03-27 12:19:20.069706', 1, 5);


--
-- TOC entry 3351 (class 0 OID 26817)
-- Dependencies: 219
-- Data for Name: topics; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.topics VALUES (3, 'string', '2024-03-27 05:42:03.928166', '2024-03-27 05:42:03.928166', 1);
INSERT INTO public.topics VALUES (4, 'Что думаете о новом компьютере?', '2024-03-27 12:19:05.629577', '2024-03-27 12:19:05.629577', 1);
INSERT INTO public.topics VALUES (5, 'Как дела?', '2024-03-27 12:19:20.067707', '2024-03-27 12:19:20.067707', 1);


--
-- TOC entry 3349 (class 0 OID 26809)
-- Dependencies: 217
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (1, 'steve', 'steve', 'string');
INSERT INTO public.users VALUES (2, 'string', 'string', 'string');


--
-- TOC entry 3359 (class 0 OID 0)
-- Dependencies: 220
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 10, true);


--
-- TOC entry 3360 (class 0 OID 0)
-- Dependencies: 218
-- Name: topics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.topics_id_seq', 5, true);


--
-- TOC entry 3361 (class 0 OID 0)
-- Dependencies: 216
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- TOC entry 3194 (class 2606 OID 26807)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 3200 (class 2606 OID 26829)
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- TOC entry 3198 (class 2606 OID 26822)
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);


--
-- TOC entry 3196 (class 2606 OID 26815)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3202 (class 2606 OID 26840)
-- Name: messages fk_message_topic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_message_topic FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;


--
-- TOC entry 3203 (class 2606 OID 26835)
-- Name: messages fk_message_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_message_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE RESTRICT;


--
-- TOC entry 3201 (class 2606 OID 26830)
-- Name: topics fk_topic_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT fk_topic_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE RESTRICT;


-- Completed on 2024-03-27 13:14:08

--
-- PostgreSQL database dump complete
--

